# permissions for end users to view standalones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: standalone-viewer-role
rules:
- apiGroups:
  - pingcap.com
  resources:
  - standalones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pingcap.com
  resources:
  - standalones/status
  verbs:
  - get
