apiVersion: pingcap.com/v1alpha1
kind: TiflowCluster
metadata:
  name: basic
spec:
  version: latest
  configUpdateStrategy: RollingUpdate
  imagePullPolicy: Always
  master:
    baseImage: gcr.io/pingcap-public/tidbcloud/tiflow
    maxFailoverCount: 0
    replicas: 3
    # if storageClassName is not set, the default Storage Class of the Kubernetes cluster will be used
    # storageClassName: local-storage
    requests:
      storage: "1Gi"
    config: |
      [framework-meta]
        schema = "example_framework"
        endpoints = ["mysql.default.svc:3306"]
        user = "root"
        password = "123456"
      [business-meta]
        schema = "example_business"
        endpoints = ["mysql.default.svc:3306"]
        user = "root"
        password = "123456"
---
apiVersion: v1
kind: Namespace
metadata:
  name: hetero-0
---
apiVersion: pingcap.com/v1alpha1
kind: TiflowCluster
metadata:
  name: hetero
  namespace: hetero-0
spec:
  version: latest
  configUpdateStrategy: RollingUpdate
  imagePullPolicy: Always
  executor:
    baseImage: gcr.io/pingcap-public/tidbcloud/tiflow
    maxFailoverCount: 0
    replicas: 3
    stateful: false
    config: |
      keepalive-ttl = "20s"
      keepalive-interval = "500ms"
  cluster:
    namespace: "default"
    name: "basic"
