apiVersion: pingcap.com/v1alpha1
kind: Standalone
metadata:
  name: standalone-sample
spec:
  name: basic
  frameStandalone:
    name: mysql
    image: mysql:latest
    size: 1
    port: 3306
  userStandalone:
    name: etcd
    size: 1
    image: quay.io/coreos/etcd
    ports:
      - 2379
      - 2380

