---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: pingcap.com/v1alpha1
kind: TiflowCluster
metadata:
  name: hete
  namespace: test
spec:
  version: latest
  configUpdateStrategy: RollingUpdate
  imagePullPolicy: Always
  cluster:
    namespace: "default"
    name: "basic"
  executor:
    baseImage: chunzhuli/dataflow
    maxFailoverCount: 0
    replicas: 3
    stateful: false
    config: |
      keepalive-ttl = "20s"
      keepalive-interval = "500ms"
      session-ttl = 20