apiVersion: pingcap.com/v1alpha1
kind: TiflowCluster
metadata:
  name: basic
spec:
  version: latest
  configUpdateStrategy: RollingUpdate
  imagePullPolicy: Always
  master:
    baseImage: chunzhuli/dataflow
    maxFailoverCount: 0
    replicas: 3
    # if storageClassName is not set, the default Storage Class of the Kubernetes cluster will be used
    # storageClassName: local-storage
    requests:
      storage: "1Gi"
    config: |
      etcd-endpoints = ["etcd:2379"]
      [framework-metastore-conf]
        schema = "example_framework"
        endpoints = ["mysql:3306"]
      [framework-metastore-conf.auth]
        user = "root"
        passwd = "123456"
      [business-metastore-conf]
        schema = "example_business"
        endpoints = ["mysql:3306"]
      [business-metastore-conf.auth]
        user = "root"
        passwd = "123456"
  executor:
    baseImage: chunzhuli/dataflow
    maxFailoverCount: 0
    replicas: 3
    stateful: false
    config: |
      keepalive-ttl = "20s"
      keepalive-interval = "500ms"
      session-ttl = 20
---
apiVersion: v1
kind: Namespace
metadata:
  name: basic-0
---
apiVersion: pingcap.com/v1alpha1
kind: TiflowCluster
metadata:
  name: basic
  namespace: basic-0
spec:
  version: latest
  configUpdateStrategy: RollingUpdate
  imagePullPolicy: Always
  executor:
    baseImage: chunzhuli/dataflow
    maxFailoverCount: 0
    replicas: 3
    stateful: false
    config: |
      keepalive-ttl = "20s"
      keepalive-interval = "500ms"
      session-ttl = 20
  cluster:
    namespace: "default"
    name: "basic"
---
apiVersion: v1
kind: Namespace
metadata:
  name: basic-1
---
apiVersion: pingcap.com/v1alpha1
kind: TiflowCluster
metadata:
  name: basic
  namespace: basic-1
spec:
  version: latest
  configUpdateStrategy: RollingUpdate
  imagePullPolicy: Always
  executor:
    baseImage: chunzhuli/dataflow
    maxFailoverCount: 0
    replicas: 3
    stateful: false
    config: |
      keepalive-ttl = "20s"
      keepalive-interval = "500ms"
      session-ttl = 20
  cluster:
    namespace: "default"
    name: "basic"
---
apiVersion: v1
kind: Namespace
metadata:
  name: basic-2
---
apiVersion: pingcap.com/v1alpha1
kind: TiflowCluster
metadata:
  name: basic
  namespace: basic-2
spec:
  version: latest
  configUpdateStrategy: RollingUpdate
  imagePullPolicy: Always
  executor:
    baseImage: chunzhuli/dataflow
    maxFailoverCount: 0
    replicas: 3
    stateful: false
    config: |
      keepalive-ttl = "20s"
      keepalive-interval = "500ms"
      session-ttl = 20
  cluster:
    namespace: "default"
    name: "basic"
